### ISSUE TITLE
Error 3080001: Account using more than allotted RAM usage

### ISSUE THREAD

**Issue by chamkaurghag** [eosdac/eosdac-factory#7]
Hi,

When running "./eosdacfactory.sh" I run into issues with setting up accounts. Whether I go the 8-character prefix route, or if I manually create all of the custodian, authority, etc. accounts (with faucet on all of them), I run into the same problem (copied below), primarily it seems that 'Error 3080001: Account using more than allotted RAM usage'. 

Any help very much appreciated!

###################

Reading WASM from /Users/cham/rhiz/eosdac-factory/eosdac-contracts/_compiled_contracts/eosdactokens/jungle/eosdactokens/eosdactokens.wasm...
Publishing contract...
Error 3080001: Account using more than allotted RAM usage
Error Details:
account rhizdac4tokn has insufficient ram; needs 536530 bytes has 5495 bytes
 >  What Token Symbol do you want to create for your DAC? rhiztoken
Error 3060003: Contract Table Query Exception
Most likely, the given table doesn't exist in the blockchain.
Error Details:
Table stat is not specified in the ABI
Token already created and issued.

Adjusting compile script for custodian contract...
Compiling custodian contract...
Set custodian contract on rhizdac4cust ...

 >>  Next command: set contract rhizdac4cust ./eosdac-contracts/_compiled_contracts/daccustodian/jungle/daccustodian -p rhizdac4cust 

 
Reading WASM from /Users/cham/rhiz/eosdac-factory/eosdac-contracts/_compiled_contracts/daccustodian/jungle/daccustodian/daccustodian.wasm...
Publishing contract...
Error 3080001: Account using more than allotted RAM usage
Error Details:
account rhizdac4cust has insufficient ram; needs 937151 bytes has 5495 bytes
Adjusting compile script for multisig contract...
Compiling multisig contract...
Warning, empty ricardian clause file
Warning, empty ricardian clause file
Warning, action <proposed> does not have a ricardian contract
Warning, action <approved> does not have a ricardian contract
Warning, action <unapproved> does not have a ricardian contract
Warning, action <cancelled> does not have a ricardian contract
Warning, action <executed> does not have a ricardian contract
Warning, action <clean> does not have a ricardian contract
Warning, action <proposed> does not have a ricardian contract
Warning, action <approved> does not have a ricardian contract
Warning, action <unapproved> does not have a ricardian contract
Warning, action <cancelled> does not have a ricardian contract
Warning, action <executed> does not have a ricardian contract
Warning, action <clean> does not have a ricardian contract
Set multisig contract on rhizdac4mult ...

 >>  Next command: set contract rhizdac4mult ./eosdac-contracts/_compiled_contracts/dacmultisigs/dacmultisigs -p rhizdac4mult 

 
Reading WASM from /Users/cham/rhiz/eosdac-factory/eosdac-contracts/_compiled_contracts/dacmultisigs/dacmultisigs/dacmultisigs.wasm...
Publishing contract...
Error 3080001: Account using more than allotted RAM usage
Error Details:
account rhizdac4mult has insufficient ram; needs 147115 bytes has 5495 bytes
Set proposals contract on rhizdac4work ...

 >>  Next command: set contract rhizdac4work ./eosdac-contracts/_compiled_contracts/dacproposals/jungle/dacproposals -p rhizdac4work 

 
Reading WASM from /Users/cham/rhiz/eosdac-factory/eosdac-contracts/_compiled_contracts/dacproposals/jungle/dacproposals/dacproposals.wasm...
Publishing contract...
Error 3080001: Account using more than allotted RAM usage
Error Details:
account rhizdac4work has insufficient ram; needs 887467 bytes has 5495 bytes
 >  Next you need a constitution. You can fork the github repo at https://github.com/eosdac/constitution to start, but ultimately you'll need to consult your own lawyers to ensure your DAC is set up according to your own legal needs. Once you have a raw markdown file of your constitution available online as a URL, enter that here. If you just want to start with our default, just hit enter to use https://raw.githubusercontent.com/eosdac/constitution/v4/constitution.md: 
--2019-08-30 13:14:53--  https://raw.githubusercontent.com/eosdac/constitution/v4/constitution.md
Resolving raw.githubusercontent.com (raw.githubusercontent.com)... 151.101.16.133
Connecting to raw.githubusercontent.com (raw.githubusercontent.com)|151.101.16.133|:443... connected.
HTTP request sent, awaiting response... 200 OK
Length: 87468 (85K) [text/plain]
Saving to: ‘constitution.md’

constitution.md                                  100%[=========================================================================================================>]  85.42K  --.-KB/s    in 0.04s   

2019-08-30 13:14:53 (2.29 MB/s) - ‘constitution.md’ saved [87468/87468]

["https://raw.githubusercontent.com/eosdac/constitution/v4/constitution.md", "be2c9d0494417cf7522cd8d6f774477c"]

 >>  Next command: push action rhizdac4tokn newmemterms terms.json -p rhizdac4tokn 

 
ABI for contract rhizdac4tokn not found. Action data will be shown in hex only.
error 2019-08-30T12:14:54.083 thread-0  main.cpp:3449                 main                 ] Failed with error: Assert Exception (10)
abis.valid(): No ABI found for rhizdac4tokn

 >>  Next command: push action rhizdac4tokn updateconfig token_config.json -p rhizdac4tokn 

 
ABI for contract rhizdac4tokn not found. Action data will be shown in hex only.
error 2019-08-30T12:14:54.272 thread-0  main.cpp:3449                 main                 ] Failed with error: Assert Exception (10)
abis.valid(): No ABI found for rhizdac4tokn

=============================================================
Time to see some configuration variables for your DAC. Just hit enter to go with the defaults
=============================================================

**Comment by michaeljyeates** [comment]
Can you pull the latest commit and try again

**Comment by michaeljyeates** [comment]
Actually, that wont work now that the account is already created.  I have bought your accounts some ram on jungle so it should work now

**Comment by str** [comment]
@michaeljyeates it's very common to try to run the dacfactory again and again, expecting to overwrite latest changes. Should the dacfactory detect if the account is created?

**Comment by michaeljyeates** [comment]
Most actions can be run many times, but yes it would be a good idea to check the current state before executing anything

**Comment by chamkaurghag** [comment]
@michaeljyeates I tried the latest commit but it didn't solve the issue. Trying again with the increased RAM that you added on the accounts, but I still get the error for account 'rhizdac4prop':

-----
Error 3080001: Account using more than allotted RAM usage
Error Details:
account rhizdac4prop has insufficient ram; needs 887467 bytes has 5495 bytes__
-----

Apologies for my naivety (new to EOS!), but I how do I allocate more RAM to the accounts myself (for if/when I repeat the process)?

Thanks!

**Comment by michaeljyeates** [comment]
I have bought some for that account too

**Comment by chamkaurghag** [comment]
Many thanks!
